# Generated by Django 5.0.6 on 2024-05-26 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('record', '0001_initial'),
        ('sections', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sections.section', verbose_name='Секция'),
        ),
    ]
